name: Deploy FastAPI to AWS Lambda

on:
  push:
    branches:
      - master  # Runs when pushing to the main branch
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install AWS CLI
        run: |
          sudo apt update
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install fastapi==0.99.0 mangum requests
          deactivate

      - name: Package and Zip for Deployment
        run: |
          mkdir package
          cp -r backend/main.py package/  # Copy your main.py file
          cp -r venv/lib/python*/site-packages/* package/  # Copy dependencies
          cd package && zip -r ../deployment.zip .  # Create zip file
          
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name thenumbergame \
            --zip-file fileb://deployment.zip \
            --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
